### ISSUE TITLE
Setting up the React user group page

### ISSUE THREAD

**Issue by pmeinhardt** [reactjs-berlin/reactjs.berlin#2]
- [x] direct reactjs.berlin domain to the GitHub page
- [x] update CNAME
- [x] update README
- [x] update icons
- [x] update HTML
  - [x] BerlinJS => ReactJS
  - [x] update content (addresses, contact information, dates…)
  - [x] empty talk slots for the next meetup
  - [x] update Google Analytics snippet
- [x] update styles/layout

**Comment by planktonic** [comment]
What’s the new google analytics snippet? (or just the ID)
